In [1]:
import pandas as pd

In [3]:
names = ['Bob', 'Jessica', 'Mary', 'John', 'Mel']
births = [968, 155, 77, 578, 973]
custom = [1, 5, 25, 13, 23232]

BabyDataSet = list(zip(names, births))
df = pd.DataFrame(data=BabyDataSet, columns=['Name', 'Births'])

df.head()

Name  Births
0      Bob     968
1  Jessica     155
2     Mary      77
3     John     578
4      Mel     973

In [4]:
df.dtypes

Name      object
Births     int64
dtype: object

In [5]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
df.columns

Index(['Name', 'Births'], dtype='object')

In [9]:
df['Name']

0        Bob
1    Jessica
2       Mary
3       John
4        Mel
Name: Name, dtype: object

In [11]:
df[df['Births'] > 100]

Name  Births
0      Bob     968
1  Jessica     155
3     John     578
4      Mel     973

In [14]:
df['Births'].mean()

np.float64(550.2)

In [15]:
import numpy as np

In [17]:
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr1.shape

(3, 5)

In [19]:
arr1.dtype

dtype('int64')

In [21]:
arr3 = np.zeros((3, 4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
arr5 = np.array([[7,8,9], [10,11,12]], dtype=np.float64)

print("arr4 + arr5 = ")
print(arr4 + arr5, '\n')
print("arr4 - arr5 = ")
print(arr4 - arr5, '\n')
print("arr4 * arr5 = ")
print(arr4 * arr5, '\n')
print("arr4 / arr5 = ")
print(arr4 / arr5, '\n')

arr4 + arr5 = 
[[ 8. 10. 12.]
 [14. 16. 18.]] 

arr4 - arr5 = 
[[-6. -6. -6.]
 [-6. -6. -6.]] 

arr4 * arr5 = 
[[ 7. 16. 27.]
 [40. 55. 72.]] 

arr4 / arr5 = 
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 

